// <auto-generated />
namespace CaseProcessor.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addcrtracking : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcrtracking));
        
        string IMigrationMetadata.Id
        {
            get { return "201708170434169_add-crtracking"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
